// Auto-generated by tinycfg_compiler.py — do not edit.
// Grammar: robot v1
#ifndef TINYCFG_ROBOT_GRAMMAR_H
#define TINYCFG_ROBOT_GRAMMAR_H

#include <stdint.h>

#define TCFG_GRAMMAR_NAME "robot"
#define TCFG_GRAMMAR_VERSION 1
#define TCFG_TERMINAL_COUNT 17
#define TCFG_NONTERMINAL_COUNT 9
#define TCFG_PRODUCTION_COUNT 22
#define TCFG_ACTION_COUNT 15

// --- Terminals ---
enum TcfgTerminal : uint8_t {
    TCFG_TOK_EOF = 0,
    TCFG_TOK_AFTER = 1,
    TCFG_TOK_AND = 2,
    TCFG_TOK_BEDROOM = 3,
    TCFG_TOK_BEFORE = 4,
    TCFG_TOK_COME = 5,
    TCFG_TOK_HERE = 6,
    TCFG_TOK_IF = 7,
    TCFG_TOK_KITCHEN = 8,
    TCFG_TOK_LIGHT = 9,
    TCFG_TOK_LIVING = 10,
    TCFG_TOK_OFF = 11,
    TCFG_TOK_ON = 12,
    TCFG_TOK_ROOM = 13,
    TCFG_TOK_STOP = 14,
    TCFG_TOK_THEN = 15,
    TCFG_TOK_TURN = 16,
    TCFG_TOK_UNTIL = 17,
    TCFG_TOK_UNKNOWN
};

// --- Non-terminals ---
enum TcfgNonTerminal : uint8_t {
    TCFG_NT_COME_HERE = 0,
    TCFG_NT_LIGHT_OFF = 1,
    TCFG_NT_LIGHT_ON = 2,
    TCFG_NT_OBJECT = 3,
    TCFG_NT_OP = 4,
    TCFG_NT_OP_REST = 5,
    TCFG_NT_STOP = 6,
    TCFG_NT_TASK = 7,
    TCFG_NT_TASK_LIST = 8,
};

// --- Semantic actions ---
enum TcfgAction : uint8_t {
    TCFG_ACT_NONE = 0,
    TCFG_ACT_LIGHT_ON = 1,
    TCFG_ACT_LIGHT_OFF = 2,
    TCFG_ACT_COME_HERE = 3,
    TCFG_ACT_STOP = 4,
    TCFG_ACT_ROOM_LIGHT = 5,
    TCFG_ACT_BEDROOM_LIGHT = 6,
    TCFG_ACT_LIVING_LIGHT = 7,
    TCFG_ACT_KITCHEN_LIGHT = 8,
    TCFG_ACT_DEFAULT_LIGHT = 9,
    TCFG_ACT_SEQ_AND = 10,
    TCFG_ACT_SEQ_THEN = 11,
    TCFG_ACT_SEQ_AFTER = 12,
    TCFG_ACT_SEQ_BEFORE = 13,
    TCFG_ACT_SEQ_IF = 14,
    TCFG_ACT_SEQ_UNTIL = 15,
};

struct TcfgSynonym { const char* word; uint8_t terminal; };
static const TcfgSynonym TCFG_SYNONYMS[] = {
    { "after", TCFG_TOK_AFTER },
    { "and", TCFG_TOK_AND },
    { "bedroom", TCFG_TOK_BEDROOM },
    { "before", TCFG_TOK_BEFORE },
    { "come", TCFG_TOK_COME },
    { "go", TCFG_TOK_COME },
    { "here", TCFG_TOK_HERE },
    { "me", TCFG_TOK_HERE },
    { "if", TCFG_TOK_IF },
    { "kitchen", TCFG_TOK_KITCHEN },
    { "light", TCFG_TOK_LIGHT },
    { "lamp", TCFG_TOK_LIGHT },
    { "living", TCFG_TOK_LIVING },
    { "off", TCFG_TOK_OFF },
    { "disable", TCFG_TOK_OFF },
    { "on", TCFG_TOK_ON },
    { "enable", TCFG_TOK_ON },
    { "room", TCFG_TOK_ROOM },
    { "stop", TCFG_TOK_STOP },
    { "halt", TCFG_TOK_STOP },
    { "freeze", TCFG_TOK_STOP },
    { "then", TCFG_TOK_THEN },
    { "turn", TCFG_TOK_TURN },
    { "switch", TCFG_TOK_TURN },
    { "activate", TCFG_TOK_TURN },
    { "until", TCFG_TOK_UNTIL },
};
static const uint8_t TCFG_SYNONYM_COUNT = 26;

struct TcfgProduction {
    uint8_t lhs;
    uint8_t rhs_len;
    uint8_t rhs[8];
    uint8_t action;
    const char* arg_template;
};

static const TcfgProduction TCFG_PRODUCTIONS[] = {
    { TCFG_NT_TASK_LIST, 2, { 7, 5, 0, 0, 0, 0, 0, 0 }, TCFG_ACT_NONE, nullptr },
    { TCFG_NT_OP_REST, 3, { 4, 7, 5, 0, 0, 0, 0, 0 }, TCFG_ACT_NONE, nullptr },
    { TCFG_NT_OP_REST, 0, { 0, 0, 0, 0, 0, 0, 0, 0 }, TCFG_ACT_NONE, nullptr },
    { TCFG_NT_TASK, 1, { 2, 0, 0, 0, 0, 0, 0, 0 }, TCFG_ACT_NONE, nullptr },
    { TCFG_NT_TASK, 1, { 1, 0, 0, 0, 0, 0, 0, 0 }, TCFG_ACT_NONE, nullptr },
    { TCFG_NT_TASK, 1, { 0, 0, 0, 0, 0, 0, 0, 0 }, TCFG_ACT_NONE, nullptr },
    { TCFG_NT_TASK, 1, { 6, 0, 0, 0, 0, 0, 0, 0 }, TCFG_ACT_NONE, nullptr },
    { TCFG_NT_LIGHT_ON, 3, { 16, 12, 3, 0, 0, 0, 0, 0 }, TCFG_ACT_LIGHT_ON, "LIGHT_ON($OBJECT)" },
    { TCFG_NT_LIGHT_OFF, 3, { 16, 11, 3, 0, 0, 0, 0, 0 }, TCFG_ACT_LIGHT_OFF, "LIGHT_OFF($OBJECT)" },
    { TCFG_NT_COME_HERE, 2, { 5, 6, 0, 0, 0, 0, 0, 0 }, TCFG_ACT_COME_HERE, nullptr },
    { TCFG_NT_STOP, 1, { 14, 0, 0, 0, 0, 0, 0, 0 }, TCFG_ACT_STOP, nullptr },
    { TCFG_NT_OBJECT, 2, { 13, 9, 0, 0, 0, 0, 0, 0 }, TCFG_ACT_ROOM_LIGHT, "room_light" },
    { TCFG_NT_OBJECT, 2, { 3, 9, 0, 0, 0, 0, 0, 0 }, TCFG_ACT_BEDROOM_LIGHT, "bedroom_light" },
    { TCFG_NT_OBJECT, 2, { 10, 9, 0, 0, 0, 0, 0, 0 }, TCFG_ACT_LIVING_LIGHT, "living_light" },
    { TCFG_NT_OBJECT, 2, { 8, 9, 0, 0, 0, 0, 0, 0 }, TCFG_ACT_KITCHEN_LIGHT, "kitchen_light" },
    { TCFG_NT_OBJECT, 1, { 9, 0, 0, 0, 0, 0, 0, 0 }, TCFG_ACT_DEFAULT_LIGHT, "default_light" },
    { TCFG_NT_OP, 1, { 2, 0, 0, 0, 0, 0, 0, 0 }, TCFG_ACT_SEQ_AND, "SEQ_AND" },
    { TCFG_NT_OP, 1, { 15, 0, 0, 0, 0, 0, 0, 0 }, TCFG_ACT_SEQ_THEN, "SEQ_THEN" },
    { TCFG_NT_OP, 1, { 1, 0, 0, 0, 0, 0, 0, 0 }, TCFG_ACT_SEQ_AFTER, "SEQ_AFTER" },
    { TCFG_NT_OP, 1, { 4, 0, 0, 0, 0, 0, 0, 0 }, TCFG_ACT_SEQ_BEFORE, "SEQ_BEFORE" },
    { TCFG_NT_OP, 1, { 7, 0, 0, 0, 0, 0, 0, 0 }, TCFG_ACT_SEQ_IF, "SEQ_IF" },
    { TCFG_NT_OP, 1, { 17, 0, 0, 0, 0, 0, 0, 0 }, TCFG_ACT_SEQ_UNTIL, "SEQ_UNTIL" },
};

// FIRST sets (terminals as TCFG_TOK_* values, 0 = epsilon)
struct TcfgFirstSet { uint8_t nt; uint8_t count; uint8_t tokens[16]; };
static const TcfgFirstSet TCFG_FIRST_SETS[] = {
    { TCFG_NT_COME_HERE, 1, { TCFG_TOK_COME, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255 } },
    { TCFG_NT_LIGHT_OFF, 1, { TCFG_TOK_TURN, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255 } },
    { TCFG_NT_LIGHT_ON, 1, { TCFG_TOK_TURN, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255 } },
    { TCFG_NT_OBJECT, 5, { TCFG_TOK_BEDROOM, TCFG_TOK_KITCHEN, TCFG_TOK_LIGHT, TCFG_TOK_LIVING, TCFG_TOK_ROOM, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255 } },
    { TCFG_NT_OP, 6, { TCFG_TOK_AFTER, TCFG_TOK_AND, TCFG_TOK_BEFORE, TCFG_TOK_IF, TCFG_TOK_THEN, TCFG_TOK_UNTIL, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255 } },
    { TCFG_NT_OP_REST, 6, { 0, TCFG_TOK_AFTER, TCFG_TOK_AND, TCFG_TOK_BEFORE, TCFG_TOK_IF, TCFG_TOK_THEN, TCFG_TOK_UNTIL, 255, 255, 255, 255, 255, 255, 255, 255, 255 } },
    { TCFG_NT_STOP, 1, { TCFG_TOK_STOP, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255 } },
    { TCFG_NT_TASK, 3, { TCFG_TOK_COME, TCFG_TOK_STOP, TCFG_TOK_TURN, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255 } },
    { TCFG_NT_TASK_LIST, 3, { TCFG_TOK_COME, TCFG_TOK_STOP, TCFG_TOK_TURN, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255 } },
};

#endif // TINYCFG_ROBOT_GRAMMAR_H
