// Auto-generated by tinycfg_compiler.py v2 — do not edit.
// Grammar: robot_nav v2
// Patterns: 10 | Terminals: 20 | Actions: 7
#ifndef TINYCFG_ROBOT_NAV_GRAMMAR_H
#define TINYCFG_ROBOT_NAV_GRAMMAR_H

#include <stdint.h>

#define TCFG_GRAMMAR_NAME "robot_nav"
#define TCFG_GRAMMAR_VERSION 2
#define TCFG_TERMINAL_COUNT 20
#define TCFG_NONTERMINAL_COUNT 5
#define TCFG_PRODUCTION_COUNT 6
#define TCFG_PATTERN_COUNT 10
#define TCFG_ACTION_COUNT 7
#define TCFG_SYNONYM_COUNT_PLACEHOLDER 0

// --- Domains (for multi-intent CDA) ---
enum TcfgDomain : uint8_t {
    TCFG_DOMAIN_GENERAL = 0,
    TCFG_DOMAIN_SMARTHOME = 1,
    TCFG_DOMAIN_ROBOT = 2,
    TCFG_DOMAIN_MEDIA = 3,
    TCFG_DOMAIN_SECURITY = 4,
    TCFG_DOMAIN_CLIMATE = 5,
    TCFG_DOMAIN_TIMER = 6,
};

// --- Terminals ---
enum TcfgTerminal : uint8_t {
    TCFG_TOK_EOF = 0,
    TCFG_TOK_AFTER = 1,
    TCFG_TOK_AND = 2,
    TCFG_TOK_BEDROOM = 3,
    TCFG_TOK_COME = 4,
    TCFG_TOK_DOCK = 5,
    TCFG_TOK_FOLLOW = 6,
    TCFG_TOK_GARAGE = 7,
    TCFG_TOK_GARDEN = 8,
    TCFG_TOK_GO = 9,
    TCFG_TOK_HALLWAY = 10,
    TCFG_TOK_HERE = 11,
    TCFG_TOK_HOME = 12,
    TCFG_TOK_KITCHEN = 13,
    TCFG_TOK_LIVING = 14,
    TCFG_TOK_OFFICE = 15,
    TCFG_TOK_PATROL = 16,
    TCFG_TOK_ROOM = 17,
    TCFG_TOK_STOP = 18,
    TCFG_TOK_THEN = 19,
    TCFG_TOK_TO = 20,
    TCFG_TOK_UNKNOWN
};

// --- Semantic actions ---
enum TcfgAction : uint8_t {
    TCFG_ACT_NONE = 0,
    TCFG_ACT_COME_HERE = 1,
    TCFG_ACT_NAV_GO = 2,
    TCFG_ACT_FOLLOW_ME = 3,
    TCFG_ACT_PATROL = 4,
    TCFG_ACT_NAV_HOME = 5,
    TCFG_ACT_NAV_DOCK = 6,
    TCFG_ACT_STOP = 7,
};

// --- Slot tokens (named device / location patterns) ---
#define TCFG_SLOT_LOCATION 240
#define TCFG_SLOT_NAME     241
#define TCFG_SLOT_DEVICE   242

static const uint8_t TCFG_LOCATION_TOKENS[] = { TCFG_TOK_KITCHEN, TCFG_TOK_BEDROOM, TCFG_TOK_LIVING, TCFG_TOK_OFFICE, TCFG_TOK_GARDEN, TCFG_TOK_GARAGE, TCFG_TOK_HALLWAY };
static const uint8_t TCFG_LOCATION_COUNT = 7;
static const uint8_t TCFG_DEVICE_TOKENS[] = {  };
static const uint8_t TCFG_DEVICE_COUNT = 0;

// --- Composition operators (N-intent) ---
static const uint8_t TCFG_OP_TOKENS[] = {
    TCFG_TOK_AND, TCFG_TOK_THEN, TCFG_TOK_AFTER,
};
static const uint8_t TCFG_OP_TOKEN_COUNT = 3;

struct TcfgSynonym { const char* word; uint8_t terminal; const char* phonetic; };
static const TcfgSynonym TCFG_SYNONYMS[] = {
    { "after", TCFG_TOK_AFTER, "A136" },
    { "and", TCFG_TOK_AND, "A530" },
    { "bedroom", TCFG_TOK_BEDROOM, "B365" },
    { "come", TCFG_TOK_COME, "C500" },
    { "go", TCFG_TOK_COME, "G000" },
    { "dock", TCFG_TOK_DOCK, "D200" },
    { "charging", TCFG_TOK_DOCK, "C625" },
    { "follow", TCFG_TOK_FOLLOW, "F400" },
    { "track", TCFG_TOK_FOLLOW, "T620" },
    { "garage", TCFG_TOK_GARAGE, "G620" },
    { "garden", TCFG_TOK_GARDEN, "G635" },
    { "go", TCFG_TOK_GO, "G000" },
    { "move", TCFG_TOK_GO, "M100" },
    { "navigate", TCFG_TOK_GO, "N123" },
    { "hallway", TCFG_TOK_HALLWAY, "H400" },
    { "here", TCFG_TOK_HERE, "H600" },
    { "me", TCFG_TOK_HERE, "M000" },
    { "home", TCFG_TOK_HOME, "H500" },
    { "base", TCFG_TOK_HOME, "B200" },
    { "kitchen", TCFG_TOK_KITCHEN, "K325" },
    { "living", TCFG_TOK_LIVING, "L152" },
    { "office", TCFG_TOK_OFFICE, "O120" },
    { "patrol", TCFG_TOK_PATROL, "P364" },
    { "guard", TCFG_TOK_PATROL, "G630" },
    { "room", TCFG_TOK_ROOM, "R500" },
    { "stop", TCFG_TOK_STOP, "S310" },
    { "halt", TCFG_TOK_STOP, "H430" },
    { "then", TCFG_TOK_THEN, "T500" },
    { "to", TCFG_TOK_TO, "T000" },
};
static const uint8_t TCFG_SYNONYM_COUNT = 29;

struct TcfgPattern {
    const uint8_t* tokens;
    uint8_t token_count;
    uint8_t action;
    const char* arg_template;
    uint8_t domain;
    uint8_t resource;
    const uint8_t* slot_types;  // 0=lit, 1=loc, 2=name, 3=device
};

enum TcfgSlotType : uint8_t { TCFG_SLOT_LIT=0, TCFG_SLOT_LOC=1, TCFG_SLOT_NM=2, TCFG_SLOT_DEV=3 };

static const uint8_t TCFG_PAT_0_TOKENS[] = { TCFG_TOK_COME, TCFG_TOK_HERE };
static const uint8_t TCFG_PAT_0_SLOTS[] = { 0, 0 };
static const uint8_t TCFG_PAT_1_TOKENS[] = { TCFG_TOK_GO, TCFG_TOK_TO, TCFG_SLOT_LOCATION };
static const uint8_t TCFG_PAT_1_SLOTS[] = { 0, 0, 1 };
static const uint8_t TCFG_PAT_2_TOKENS[] = { TCFG_TOK_GO, TCFG_TOK_TO, TCFG_SLOT_LOCATION, TCFG_TOK_ROOM };
static const uint8_t TCFG_PAT_2_SLOTS[] = { 0, 0, 1, 0 };
static const uint8_t TCFG_PAT_3_TOKENS[] = { TCFG_TOK_GO, TCFG_TOK_TO, TCFG_SLOT_NAME, TCFG_TOK_ROOM };
static const uint8_t TCFG_PAT_3_SLOTS[] = { 0, 0, 2, 0 };
static const uint8_t TCFG_PAT_4_TOKENS[] = { TCFG_TOK_GO, TCFG_TOK_TO, TCFG_SLOT_NAME, TCFG_SLOT_LOCATION };
static const uint8_t TCFG_PAT_4_SLOTS[] = { 0, 0, 2, 1 };
static const uint8_t TCFG_PAT_5_TOKENS[] = { TCFG_TOK_FOLLOW, TCFG_TOK_UNKNOWN };
static const uint8_t TCFG_PAT_5_SLOTS[] = { 0, 0 };
static const uint8_t TCFG_PAT_6_TOKENS[] = { TCFG_TOK_PATROL, TCFG_SLOT_LOCATION };
static const uint8_t TCFG_PAT_6_SLOTS[] = { 0, 1 };
static const uint8_t TCFG_PAT_7_TOKENS[] = { TCFG_TOK_GO, TCFG_TOK_HOME };
static const uint8_t TCFG_PAT_7_SLOTS[] = { 0, 0 };
static const uint8_t TCFG_PAT_8_TOKENS[] = { TCFG_TOK_DOCK };
static const uint8_t TCFG_PAT_8_SLOTS[] = { 0 };
static const uint8_t TCFG_PAT_9_TOKENS[] = { TCFG_TOK_STOP };
static const uint8_t TCFG_PAT_9_SLOTS[] = { 0 };

static const TcfgPattern TCFG_PATTERNS[] = {
    { TCFG_PAT_0_TOKENS, 2, TCFG_ACT_COME_HERE, nullptr, 2, 6, TCFG_PAT_0_SLOTS },
    { TCFG_PAT_1_TOKENS, 3, TCFG_ACT_NAV_GO, "{location}", 2, 6, TCFG_PAT_1_SLOTS },
    { TCFG_PAT_2_TOKENS, 4, TCFG_ACT_NAV_GO, "{location}", 2, 6, TCFG_PAT_2_SLOTS },
    { TCFG_PAT_3_TOKENS, 4, TCFG_ACT_NAV_GO, "{name}_room", 2, 6, TCFG_PAT_3_SLOTS },
    { TCFG_PAT_4_TOKENS, 4, TCFG_ACT_NAV_GO, "{name}_{location}", 2, 6, TCFG_PAT_4_SLOTS },
    { TCFG_PAT_5_TOKENS, 2, TCFG_ACT_FOLLOW_ME, nullptr, 2, 6, TCFG_PAT_5_SLOTS },
    { TCFG_PAT_6_TOKENS, 2, TCFG_ACT_PATROL, "{location}", 2, 6, TCFG_PAT_6_SLOTS },
    { TCFG_PAT_7_TOKENS, 2, TCFG_ACT_NAV_HOME, nullptr, 2, 6, TCFG_PAT_7_SLOTS },
    { TCFG_PAT_8_TOKENS, 1, TCFG_ACT_NAV_DOCK, nullptr, 2, 6, TCFG_PAT_8_SLOTS },
    { TCFG_PAT_9_TOKENS, 1, TCFG_ACT_STOP, nullptr, 2, 6, TCFG_PAT_9_SLOTS },
};

static const char* TCFG_ACTION_NAMES[] = {
    "NONE",
    "COME_HERE",
    "NAV_GO",
    "FOLLOW_ME",
    "PATROL",
    "NAV_HOME",
    "NAV_DOCK",
    "STOP",
};

static const char* TCFG_DOMAIN_NAMES[] = {
    "general", "smarthome", "robot", "media", "security", "climate", "timer",
};

#endif // TINYCFG_ROBOT_NAV_GRAMMAR_H
