// Auto-generated by tinycfg_compiler.py v2 — do not edit.
// Grammar: smarthome v2
// Patterns: 18 | Terminals: 25 | Actions: 9
#ifndef TINYCFG_SMARTHOME_GRAMMAR_H
#define TINYCFG_SMARTHOME_GRAMMAR_H

#include <stdint.h>

#define TCFG_GRAMMAR_NAME "smarthome"
#define TCFG_GRAMMAR_VERSION 2
#define TCFG_TERMINAL_COUNT 25
#define TCFG_NONTERMINAL_COUNT 5
#define TCFG_PRODUCTION_COUNT 5
#define TCFG_PATTERN_COUNT 18
#define TCFG_ACTION_COUNT 9
#define TCFG_SYNONYM_COUNT_PLACEHOLDER 0

// --- Domains (for multi-intent CDA) ---
enum TcfgDomain : uint8_t {
    TCFG_DOMAIN_GENERAL = 0,
    TCFG_DOMAIN_SMARTHOME = 1,
    TCFG_DOMAIN_ROBOT = 2,
    TCFG_DOMAIN_MEDIA = 3,
    TCFG_DOMAIN_SECURITY = 4,
    TCFG_DOMAIN_CLIMATE = 5,
    TCFG_DOMAIN_TIMER = 6,
};

// --- Terminals ---
enum TcfgTerminal : uint8_t {
    TCFG_TOK_EOF = 0,
    TCFG_TOK_AND = 1,
    TCFG_TOK_BACK = 2,
    TCFG_TOK_BATHROOM = 3,
    TCFG_TOK_BEDROOM = 4,
    TCFG_TOK_CLOSE = 5,
    TCFG_TOK_CURTAIN = 6,
    TCFG_TOK_DOOR = 7,
    TCFG_TOK_FAN = 8,
    TCFG_TOK_FRONT = 9,
    TCFG_TOK_GARAGE = 10,
    TCFG_TOK_KITCHEN = 11,
    TCFG_TOK_LIGHT = 12,
    TCFG_TOK_LIVING = 13,
    TCFG_TOK_LOCK = 14,
    TCFG_TOK_MOVIE = 15,
    TCFG_TOK_NIGHT = 16,
    TCFG_TOK_OFF = 17,
    TCFG_TOK_OFFICE = 18,
    TCFG_TOK_ON = 19,
    TCFG_TOK_OPEN = 20,
    TCFG_TOK_ROOM = 21,
    TCFG_TOK_SCENE = 22,
    TCFG_TOK_THEN = 23,
    TCFG_TOK_TURN = 24,
    TCFG_TOK_UNLOCK = 25,
    TCFG_TOK_UNKNOWN
};

// --- Semantic actions ---
enum TcfgAction : uint8_t {
    TCFG_ACT_NONE = 0,
    TCFG_ACT_LIGHT_ON = 1,
    TCFG_ACT_LIGHT_OFF = 2,
    TCFG_ACT_FAN_ON = 3,
    TCFG_ACT_FAN_OFF = 4,
    TCFG_ACT_LOCK = 5,
    TCFG_ACT_UNLOCK = 6,
    TCFG_ACT_CURTAIN_OPEN = 7,
    TCFG_ACT_CURTAIN_CLOSE = 8,
    TCFG_ACT_SCENE = 9,
};

// --- Slot tokens (named device / location patterns) ---
#define TCFG_SLOT_LOCATION 240
#define TCFG_SLOT_NAME     241
#define TCFG_SLOT_DEVICE   242

static const uint8_t TCFG_LOCATION_TOKENS[] = { TCFG_TOK_ROOM, TCFG_TOK_BEDROOM, TCFG_TOK_KITCHEN, TCFG_TOK_LIVING, TCFG_TOK_BATHROOM, TCFG_TOK_GARAGE, TCFG_TOK_OFFICE, TCFG_TOK_FRONT, TCFG_TOK_BACK };
static const uint8_t TCFG_LOCATION_COUNT = 9;
static const uint8_t TCFG_DEVICE_TOKENS[] = { TCFG_TOK_FAN, TCFG_TOK_LIGHT, TCFG_TOK_DOOR, TCFG_TOK_CURTAIN };
static const uint8_t TCFG_DEVICE_COUNT = 4;

// --- Composition operators (N-intent) ---
static const uint8_t TCFG_OP_TOKENS[] = {
    TCFG_TOK_AND, TCFG_TOK_THEN,
};
static const uint8_t TCFG_OP_TOKEN_COUNT = 2;

struct TcfgSynonym { const char* word; uint8_t terminal; const char* phonetic; };
static const TcfgSynonym TCFG_SYNONYMS[] = {
    { "and", TCFG_TOK_AND, "A530" },
    { "back", TCFG_TOK_BACK, "B200" },
    { "bathroom", TCFG_TOK_BATHROOM, "B365" },
    { "bedroom", TCFG_TOK_BEDROOM, "B365" },
    { "close", TCFG_TOK_CLOSE, "C420" },
    { "curtain", TCFG_TOK_CURTAIN, "C635" },
    { "door", TCFG_TOK_DOOR, "D600" },
    { "fan", TCFG_TOK_FAN, "F500" },
    { "front", TCFG_TOK_FRONT, "F653" },
    { "garage", TCFG_TOK_GARAGE, "G620" },
    { "kitchen", TCFG_TOK_KITCHEN, "K325" },
    { "light", TCFG_TOK_LIGHT, "L230" },
    { "lamp", TCFG_TOK_LIGHT, "L510" },
    { "living", TCFG_TOK_LIVING, "L152" },
    { "lock", TCFG_TOK_LOCK, "L200" },
    { "movie", TCFG_TOK_MOVIE, "M100" },
    { "night", TCFG_TOK_NIGHT, "N230" },
    { "off", TCFG_TOK_OFF, "O100" },
    { "disable", TCFG_TOK_OFF, "D214" },
    { "office", TCFG_TOK_OFFICE, "O120" },
    { "on", TCFG_TOK_ON, "O500" },
    { "enable", TCFG_TOK_ON, "E514" },
    { "open", TCFG_TOK_OPEN, "O150" },
    { "room", TCFG_TOK_ROOM, "R500" },
    { "scene", TCFG_TOK_SCENE, "S250" },
    { "then", TCFG_TOK_THEN, "T500" },
    { "turn", TCFG_TOK_TURN, "T650" },
    { "switch", TCFG_TOK_TURN, "S320" },
    { "unlock", TCFG_TOK_UNLOCK, "U542" },
};
static const uint8_t TCFG_SYNONYM_COUNT = 29;

struct TcfgPattern {
    const uint8_t* tokens;
    uint8_t token_count;
    uint8_t action;
    const char* arg_template;
    uint8_t domain;
    uint8_t resource;
    const uint8_t* slot_types;  // 0=lit, 1=loc, 2=name, 3=device
};

enum TcfgSlotType : uint8_t { TCFG_SLOT_LIT=0, TCFG_SLOT_LOC=1, TCFG_SLOT_NM=2, TCFG_SLOT_DEV=3 };

static const uint8_t TCFG_PAT_0_TOKENS[] = { TCFG_TOK_TURN, TCFG_TOK_ON, TCFG_SLOT_LOCATION, TCFG_TOK_LIGHT };
static const uint8_t TCFG_PAT_0_SLOTS[] = { 0, 0, 1, 0 };
static const uint8_t TCFG_PAT_1_TOKENS[] = { TCFG_TOK_TURN, TCFG_TOK_ON, TCFG_SLOT_NAME, TCFG_SLOT_LOCATION, TCFG_TOK_LIGHT };
static const uint8_t TCFG_PAT_1_SLOTS[] = { 0, 0, 2, 1, 0 };
static const uint8_t TCFG_PAT_2_TOKENS[] = { TCFG_TOK_TURN, TCFG_TOK_ON, TCFG_SLOT_NAME, TCFG_TOK_LIGHT };
static const uint8_t TCFG_PAT_2_SLOTS[] = { 0, 0, 2, 0 };
static const uint8_t TCFG_PAT_3_TOKENS[] = { TCFG_TOK_TURN, TCFG_TOK_OFF, TCFG_SLOT_LOCATION, TCFG_TOK_LIGHT };
static const uint8_t TCFG_PAT_3_SLOTS[] = { 0, 0, 1, 0 };
static const uint8_t TCFG_PAT_4_TOKENS[] = { TCFG_TOK_TURN, TCFG_TOK_OFF, TCFG_SLOT_NAME, TCFG_SLOT_LOCATION, TCFG_TOK_LIGHT };
static const uint8_t TCFG_PAT_4_SLOTS[] = { 0, 0, 2, 1, 0 };
static const uint8_t TCFG_PAT_5_TOKENS[] = { TCFG_TOK_TURN, TCFG_TOK_ON, TCFG_SLOT_LOCATION, TCFG_TOK_FAN };
static const uint8_t TCFG_PAT_5_SLOTS[] = { 0, 0, 1, 0 };
static const uint8_t TCFG_PAT_6_TOKENS[] = { TCFG_TOK_TURN, TCFG_TOK_ON, TCFG_SLOT_NAME, TCFG_SLOT_LOCATION, TCFG_TOK_FAN };
static const uint8_t TCFG_PAT_6_SLOTS[] = { 0, 0, 2, 1, 0 };
static const uint8_t TCFG_PAT_7_TOKENS[] = { TCFG_TOK_TURN, TCFG_TOK_ON, TCFG_SLOT_NAME, TCFG_TOK_FAN };
static const uint8_t TCFG_PAT_7_SLOTS[] = { 0, 0, 2, 0 };
static const uint8_t TCFG_PAT_8_TOKENS[] = { TCFG_TOK_TURN, TCFG_TOK_OFF, TCFG_SLOT_LOCATION, TCFG_TOK_FAN };
static const uint8_t TCFG_PAT_8_SLOTS[] = { 0, 0, 1, 0 };
static const uint8_t TCFG_PAT_9_TOKENS[] = { TCFG_TOK_TURN, TCFG_TOK_OFF, TCFG_SLOT_NAME, TCFG_SLOT_LOCATION, TCFG_TOK_FAN };
static const uint8_t TCFG_PAT_9_SLOTS[] = { 0, 0, 2, 1, 0 };
static const uint8_t TCFG_PAT_10_TOKENS[] = { TCFG_TOK_LOCK, TCFG_SLOT_LOCATION, TCFG_TOK_DOOR };
static const uint8_t TCFG_PAT_10_SLOTS[] = { 0, 1, 0 };
static const uint8_t TCFG_PAT_11_TOKENS[] = { TCFG_TOK_LOCK, TCFG_SLOT_NAME, TCFG_TOK_DOOR };
static const uint8_t TCFG_PAT_11_SLOTS[] = { 0, 2, 0 };
static const uint8_t TCFG_PAT_12_TOKENS[] = { TCFG_TOK_UNLOCK, TCFG_SLOT_LOCATION, TCFG_TOK_DOOR };
static const uint8_t TCFG_PAT_12_SLOTS[] = { 0, 1, 0 };
static const uint8_t TCFG_PAT_13_TOKENS[] = { TCFG_TOK_UNLOCK, TCFG_SLOT_NAME, TCFG_TOK_DOOR };
static const uint8_t TCFG_PAT_13_SLOTS[] = { 0, 2, 0 };
static const uint8_t TCFG_PAT_14_TOKENS[] = { TCFG_TOK_OPEN, TCFG_SLOT_LOCATION, TCFG_TOK_CURTAIN };
static const uint8_t TCFG_PAT_14_SLOTS[] = { 0, 1, 0 };
static const uint8_t TCFG_PAT_15_TOKENS[] = { TCFG_TOK_CLOSE, TCFG_SLOT_LOCATION, TCFG_TOK_CURTAIN };
static const uint8_t TCFG_PAT_15_SLOTS[] = { 0, 1, 0 };
static const uint8_t TCFG_PAT_16_TOKENS[] = { TCFG_TOK_SCENE, TCFG_TOK_MOVIE };
static const uint8_t TCFG_PAT_16_SLOTS[] = { 0, 0 };
static const uint8_t TCFG_PAT_17_TOKENS[] = { TCFG_TOK_SCENE, TCFG_TOK_NIGHT };
static const uint8_t TCFG_PAT_17_SLOTS[] = { 0, 0 };

static const TcfgPattern TCFG_PATTERNS[] = {
    { TCFG_PAT_0_TOKENS, 4, TCFG_ACT_LIGHT_ON, "{location}_light", 1, 1, TCFG_PAT_0_SLOTS },
    { TCFG_PAT_1_TOKENS, 5, TCFG_ACT_LIGHT_ON, "{name}_{location}_light", 1, 1, TCFG_PAT_1_SLOTS },
    { TCFG_PAT_2_TOKENS, 4, TCFG_ACT_LIGHT_ON, "{name}_light", 1, 1, TCFG_PAT_2_SLOTS },
    { TCFG_PAT_3_TOKENS, 4, TCFG_ACT_LIGHT_OFF, "{location}_light", 1, 1, TCFG_PAT_3_SLOTS },
    { TCFG_PAT_4_TOKENS, 5, TCFG_ACT_LIGHT_OFF, "{name}_{location}_light", 1, 1, TCFG_PAT_4_SLOTS },
    { TCFG_PAT_5_TOKENS, 4, TCFG_ACT_FAN_ON, "{location}_fan", 1, 2, TCFG_PAT_5_SLOTS },
    { TCFG_PAT_6_TOKENS, 5, TCFG_ACT_FAN_ON, "{name}_{location}_fan", 1, 2, TCFG_PAT_6_SLOTS },
    { TCFG_PAT_7_TOKENS, 4, TCFG_ACT_FAN_ON, "{name}_fan", 1, 2, TCFG_PAT_7_SLOTS },
    { TCFG_PAT_8_TOKENS, 4, TCFG_ACT_FAN_OFF, "{location}_fan", 1, 2, TCFG_PAT_8_SLOTS },
    { TCFG_PAT_9_TOKENS, 5, TCFG_ACT_FAN_OFF, "{name}_{location}_fan", 1, 2, TCFG_PAT_9_SLOTS },
    { TCFG_PAT_10_TOKENS, 3, TCFG_ACT_LOCK, "{location}_door", 1, 3, TCFG_PAT_10_SLOTS },
    { TCFG_PAT_11_TOKENS, 3, TCFG_ACT_LOCK, "{name}_door", 1, 3, TCFG_PAT_11_SLOTS },
    { TCFG_PAT_12_TOKENS, 3, TCFG_ACT_UNLOCK, "{location}_door", 1, 3, TCFG_PAT_12_SLOTS },
    { TCFG_PAT_13_TOKENS, 3, TCFG_ACT_UNLOCK, "{name}_door", 1, 3, TCFG_PAT_13_SLOTS },
    { TCFG_PAT_14_TOKENS, 3, TCFG_ACT_CURTAIN_OPEN, "{location}", 1, 4, TCFG_PAT_14_SLOTS },
    { TCFG_PAT_15_TOKENS, 3, TCFG_ACT_CURTAIN_CLOSE, "{location}", 1, 4, TCFG_PAT_15_SLOTS },
    { TCFG_PAT_16_TOKENS, 2, TCFG_ACT_SCENE, "movie", 1, 5, TCFG_PAT_16_SLOTS },
    { TCFG_PAT_17_TOKENS, 2, TCFG_ACT_SCENE, "night", 1, 5, TCFG_PAT_17_SLOTS },
};

static const char* TCFG_ACTION_NAMES[] = {
    "NONE",
    "LIGHT_ON",
    "LIGHT_OFF",
    "FAN_ON",
    "FAN_OFF",
    "LOCK",
    "UNLOCK",
    "CURTAIN_OPEN",
    "CURTAIN_CLOSE",
    "SCENE",
};

static const char* TCFG_DOMAIN_NAMES[] = {
    "general", "smarthome", "robot", "media", "security", "climate", "timer",
};

#endif // TINYCFG_SMARTHOME_GRAMMAR_H
