// Auto-generated by tinycfg_compiler.py v2 — do not edit.
// Grammar: smart_world v3
// Patterns: 74 | Terminals: 82 | Actions: 44
#ifndef TINYCFG_SMART_WORLD_GRAMMAR_H
#define TINYCFG_SMART_WORLD_GRAMMAR_H

#include <stdint.h>

#define TCFG_GRAMMAR_NAME "smart_world"
#define TCFG_GRAMMAR_VERSION 3
#define TCFG_TERMINAL_COUNT 82
#define TCFG_NONTERMINAL_COUNT 6
#define TCFG_PRODUCTION_COUNT 12
#define TCFG_PATTERN_COUNT 74
#define TCFG_ACTION_COUNT 44
#define TCFG_SYNONYM_COUNT_PLACEHOLDER 0

// --- Domains (for multi-intent CDA) ---
enum TcfgDomain : uint8_t {
    TCFG_DOMAIN_GENERAL = 0,
    TCFG_DOMAIN_SMARTHOME = 1,
    TCFG_DOMAIN_ROBOT = 2,
    TCFG_DOMAIN_MEDIA = 3,
    TCFG_DOMAIN_SECURITY = 4,
    TCFG_DOMAIN_CLIMATE = 5,
    TCFG_DOMAIN_TIMER = 6,
};

// --- Terminals ---
enum TcfgTerminal : uint8_t {
    TCFG_TOK_EOF = 0,
    TCFG_TOK_AFTER = 1,
    TCFG_TOK_ALARM = 2,
    TCFG_TOK_AND = 3,
    TCFG_TOK_ARM = 4,
    TCFG_TOK_BACK = 5,
    TCFG_TOK_BATHROOM = 6,
    TCFG_TOK_BEDROOM = 7,
    TCFG_TOK_BEFORE = 8,
    TCFG_TOK_CAMERA = 9,
    TCFG_TOK_CHECK = 10,
    TCFG_TOK_CLOSE = 11,
    TCFG_TOK_COME = 12,
    TCFG_TOK_COOL = 13,
    TCFG_TOK_CURTAIN = 14,
    TCFG_TOK_DEGREES = 15,
    TCFG_TOK_DISARM = 16,
    TCFG_TOK_DOCK = 17,
    TCFG_TOK_DOOR = 18,
    TCFG_TOK_DOWN = 19,
    TCFG_TOK_FAN = 20,
    TCFG_TOK_FIFTEEN = 21,
    TCFG_TOK_FIVE = 22,
    TCFG_TOK_FOLLOW = 23,
    TCFG_TOK_FOR = 24,
    TCFG_TOK_FRONT = 25,
    TCFG_TOK_GARAGE = 26,
    TCFG_TOK_GARDEN = 27,
    TCFG_TOK_GO = 28,
    TCFG_TOK_HALLWAY = 29,
    TCFG_TOK_HEAT = 30,
    TCFG_TOK_HERE = 31,
    TCFG_TOK_HOME = 32,
    TCFG_TOK_IF = 33,
    TCFG_TOK_IN = 34,
    TCFG_TOK_KITCHEN = 35,
    TCFG_TOK_LIGHT = 36,
    TCFG_TOK_LIVING = 37,
    TCFG_TOK_LOCK = 38,
    TCFG_TOK_MINUTE = 39,
    TCFG_TOK_MINUTES = 40,
    TCFG_TOK_MOVIE = 41,
    TCFG_TOK_MUTE = 42,
    TCFG_TOK_NEXT = 43,
    TCFG_TOK_NIGHT = 44,
    TCFG_TOK_OFF = 45,
    TCFG_TOK_OFFICE = 46,
    TCFG_TOK_ON = 47,
    TCFG_TOK_ONE = 48,
    TCFG_TOK_OPEN = 49,
    TCFG_TOK_OR = 50,
    TCFG_TOK_PARTY = 51,
    TCFG_TOK_PATROL = 52,
    TCFG_TOK_PAUSE = 53,
    TCFG_TOK_PLAY = 54,
    TCFG_TOK_PLAYLIST = 55,
    TCFG_TOK_PREVIOUS = 56,
    TCFG_TOK_RADIO = 57,
    TCFG_TOK_RECORD = 58,
    TCFG_TOK_ROOM = 59,
    TCFG_TOK_SCENE = 60,
    TCFG_TOK_SECOND = 61,
    TCFG_TOK_SECONDS = 62,
    TCFG_TOK_SET = 63,
    TCFG_TOK_SEVENTY = 64,
    TCFG_TOK_SONG = 65,
    TCFG_TOK_STOP = 66,
    TCFG_TOK_TEN = 67,
    TCFG_TOK_THEN = 68,
    TCFG_TOK_THERMOSTAT = 69,
    TCFG_TOK_THIRTY = 70,
    TCFG_TOK_THREE = 71,
    TCFG_TOK_TIMER = 72,
    TCFG_TOK_TO = 73,
    TCFG_TOK_TURN = 74,
    TCFG_TOK_TWO = 75,
    TCFG_TOK_UNLOCK = 76,
    TCFG_TOK_UNMUTE = 77,
    TCFG_TOK_UNTIL = 78,
    TCFG_TOK_UP = 79,
    TCFG_TOK_VOLUME = 80,
    TCFG_TOK_WAIT = 81,
    TCFG_TOK_WHILE = 82,
    TCFG_TOK_UNKNOWN
};

// --- Semantic actions ---
enum TcfgAction : uint8_t {
    TCFG_ACT_NONE = 0,
    TCFG_ACT_SEQ_AND = 1,
    TCFG_ACT_SEQ_THEN = 2,
    TCFG_ACT_SEQ_AFTER = 3,
    TCFG_ACT_SEQ_BEFORE = 4,
    TCFG_ACT_SEQ_IF = 5,
    TCFG_ACT_SEQ_UNTIL = 6,
    TCFG_ACT_SEQ_WHILE = 7,
    TCFG_ACT_LIGHT_ON = 8,
    TCFG_ACT_LIGHT_OFF = 9,
    TCFG_ACT_FAN_ON = 10,
    TCFG_ACT_FAN_OFF = 11,
    TCFG_ACT_LOCK = 12,
    TCFG_ACT_UNLOCK = 13,
    TCFG_ACT_CURTAIN_OPEN = 14,
    TCFG_ACT_CURTAIN_CLOSE = 15,
    TCFG_ACT_SCENE = 16,
    TCFG_ACT_COME_HERE = 17,
    TCFG_ACT_NAV_GO = 18,
    TCFG_ACT_FOLLOW_ME = 19,
    TCFG_ACT_PATROL = 20,
    TCFG_ACT_NAV_HOME = 21,
    TCFG_ACT_NAV_DOCK = 22,
    TCFG_ACT_STOP = 23,
    TCFG_ACT_WAIT = 24,
    TCFG_ACT_MEDIA_PLAY = 25,
    TCFG_ACT_MEDIA_PAUSE = 26,
    TCFG_ACT_VOLUME_UP = 27,
    TCFG_ACT_VOLUME_DOWN = 28,
    TCFG_ACT_MUTE = 29,
    TCFG_ACT_UNMUTE = 30,
    TCFG_ACT_NEXT_TRACK = 31,
    TCFG_ACT_PREV_TRACK = 32,
    TCFG_ACT_ALARM_ARM = 33,
    TCFG_ACT_ALARM_DISARM = 34,
    TCFG_ACT_CAMERA_VIEW = 35,
    TCFG_ACT_CAMERA_RECORD = 36,
    TCFG_ACT_TEMP_SET = 37,
    TCFG_ACT_TEMP_ZONE = 38,
    TCFG_ACT_TEMP_UP = 39,
    TCFG_ACT_TEMP_DOWN = 40,
    TCFG_ACT_HEAT_ON = 41,
    TCFG_ACT_COOL_ON = 42,
    TCFG_ACT_TIMER_SET = 43,
    TCFG_ACT_TIMER_CANCEL = 44,
};

// --- Slot tokens (named device / location patterns) ---
#define TCFG_SLOT_LOCATION 240
#define TCFG_SLOT_NAME     241
#define TCFG_SLOT_DEVICE   242

static const uint8_t TCFG_LOCATION_TOKENS[] = { TCFG_TOK_ROOM, TCFG_TOK_BEDROOM, TCFG_TOK_LIVING, TCFG_TOK_KITCHEN, TCFG_TOK_BATHROOM, TCFG_TOK_GARAGE, TCFG_TOK_OFFICE, TCFG_TOK_HALLWAY, TCFG_TOK_GARDEN, TCFG_TOK_FRONT, TCFG_TOK_BACK };
static const uint8_t TCFG_LOCATION_COUNT = 11;
static const uint8_t TCFG_DEVICE_TOKENS[] = { TCFG_TOK_FAN, TCFG_TOK_LIGHT, TCFG_TOK_DOOR, TCFG_TOK_CURTAIN, TCFG_TOK_CAMERA, TCFG_TOK_THERMOSTAT };
static const uint8_t TCFG_DEVICE_COUNT = 6;

// --- Composition operators (N-intent) ---
static const uint8_t TCFG_OP_TOKENS[] = {
    TCFG_TOK_AND, TCFG_TOK_OR, TCFG_TOK_THEN, TCFG_TOK_AFTER, TCFG_TOK_BEFORE, TCFG_TOK_IF, TCFG_TOK_UNTIL, TCFG_TOK_WHILE,
};
static const uint8_t TCFG_OP_TOKEN_COUNT = 8;

struct TcfgSynonym { const char* word; uint8_t terminal; const char* phonetic; };
static const TcfgSynonym TCFG_SYNONYMS[] = {
    { "after", TCFG_TOK_AFTER, "A136" },
    { "alarm", TCFG_TOK_ALARM, "A465" },
    { "security", TCFG_TOK_ALARM, "S263" },
    { "and", TCFG_TOK_AND, "A530" },
    { "arm", TCFG_TOK_ARM, "A650" },
    { "enable", TCFG_TOK_ARM, "E514" },
    { "back", TCFG_TOK_BACK, "B200" },
    { "bathroom", TCFG_TOK_BATHROOM, "B365" },
    { "washroom", TCFG_TOK_BATHROOM, "W265" },
    { "bedroom", TCFG_TOK_BEDROOM, "B365" },
    { "before", TCFG_TOK_BEFORE, "B160" },
    { "camera", TCFG_TOK_CAMERA, "C560" },
    { "cameras", TCFG_TOK_CAMERA, "C562" },
    { "cctv", TCFG_TOK_CAMERA, "C231" },
    { "check", TCFG_TOK_CHECK, "C200" },
    { "show", TCFG_TOK_CHECK, "S000" },
    { "view", TCFG_TOK_CHECK, "V000" },
    { "display", TCFG_TOK_CHECK, "D214" },
    { "close", TCFG_TOK_CLOSE, "C420" },
    { "shut", TCFG_TOK_CLOSE, "S300" },
    { "come", TCFG_TOK_COME, "C500" },
    { "cool", TCFG_TOK_COOL, "C400" },
    { "cooling", TCFG_TOK_COOL, "C452" },
    { "cold", TCFG_TOK_COOL, "C430" },
    { "curtain", TCFG_TOK_CURTAIN, "C635" },
    { "blinds", TCFG_TOK_CURTAIN, "B453" },
    { "shade", TCFG_TOK_CURTAIN, "S300" },
    { "degrees", TCFG_TOK_DEGREES, "D262" },
    { "degree", TCFG_TOK_DEGREES, "D260" },
    { "disarm", TCFG_TOK_DISARM, "D265" },
    { "disable", TCFG_TOK_DISARM, "D214" },
    { "dock", TCFG_TOK_DOCK, "D200" },
    { "charging", TCFG_TOK_DOCK, "C625" },
    { "door", TCFG_TOK_DOOR, "D600" },
    { "down", TCFG_TOK_DOWN, "D500" },
    { "quieter", TCFG_TOK_DOWN, "Q360" },
    { "decrease", TCFG_TOK_DOWN, "D262" },
    { "lower", TCFG_TOK_DOWN, "L600" },
    { "fan", TCFG_TOK_FAN, "F500" },
    { "ceiling", TCFG_TOK_FAN, "C452" },
    { "fifteen", TCFG_TOK_FIFTEEN, "F135" },
    { "15", TCFG_TOK_FIFTEEN, "1000" },
    { "five", TCFG_TOK_FIVE, "F100" },
    { "5", TCFG_TOK_FIVE, "5000" },
    { "follow", TCFG_TOK_FOLLOW, "F400" },
    { "track", TCFG_TOK_FOLLOW, "T620" },
    { "for", TCFG_TOK_FOR, "F600" },
    { "front", TCFG_TOK_FRONT, "F653" },
    { "garage", TCFG_TOK_GARAGE, "G620" },
    { "garden", TCFG_TOK_GARDEN, "G635" },
    { "yard", TCFG_TOK_GARDEN, "Y630" },
    { "backyard", TCFG_TOK_GARDEN, "B263" },
    { "go", TCFG_TOK_GO, "G000" },
    { "move", TCFG_TOK_GO, "M100" },
    { "navigate", TCFG_TOK_GO, "N123" },
    { "drive", TCFG_TOK_GO, "D610" },
    { "hallway", TCFG_TOK_HALLWAY, "H400" },
    { "corridor", TCFG_TOK_HALLWAY, "C636" },
    { "heat", TCFG_TOK_HEAT, "H300" },
    { "heating", TCFG_TOK_HEAT, "H352" },
    { "warm", TCFG_TOK_HEAT, "W650" },
    { "here", TCFG_TOK_HERE, "H600" },
    { "me", TCFG_TOK_HERE, "M000" },
    { "home", TCFG_TOK_HOME, "H500" },
    { "base", TCFG_TOK_HOME, "B200" },
    { "dock", TCFG_TOK_HOME, "D200" },
    { "if", TCFG_TOK_IF, "I100" },
    { "in", TCFG_TOK_IN, "I500" },
    { "kitchen", TCFG_TOK_KITCHEN, "K325" },
    { "light", TCFG_TOK_LIGHT, "L230" },
    { "lamp", TCFG_TOK_LIGHT, "L510" },
    { "lights", TCFG_TOK_LIGHT, "L232" },
    { "living", TCFG_TOK_LIVING, "L152" },
    { "lounge", TCFG_TOK_LIVING, "L520" },
    { "lock", TCFG_TOK_LOCK, "L200" },
    { "minute", TCFG_TOK_MINUTE, "M530" },
    { "minutes", TCFG_TOK_MINUTE, "M532" },
    { "min", TCFG_TOK_MINUTE, "M500" },
    { "minutes", TCFG_TOK_MINUTES, "M532" },
    { "movie", TCFG_TOK_MOVIE, "M100" },
    { "cinema", TCFG_TOK_MOVIE, "C500" },
    { "film", TCFG_TOK_MOVIE, "F450" },
    { "mute", TCFG_TOK_MUTE, "M300" },
    { "silence", TCFG_TOK_MUTE, "S452" },
    { "next", TCFG_TOK_NEXT, "N230" },
    { "skip", TCFG_TOK_NEXT, "S210" },
    { "night", TCFG_TOK_NIGHT, "N230" },
    { "sleep", TCFG_TOK_NIGHT, "S410" },
    { "bedtime", TCFG_TOK_NIGHT, "B350" },
    { "off", TCFG_TOK_OFF, "O100" },
    { "disable", TCFG_TOK_OFF, "D214" },
    { "office", TCFG_TOK_OFFICE, "O120" },
    { "study", TCFG_TOK_OFFICE, "S300" },
    { "on", TCFG_TOK_ON, "O500" },
    { "enable", TCFG_TOK_ON, "E514" },
    { "one", TCFG_TOK_ONE, "O500" },
    { "1", TCFG_TOK_ONE, "1000" },
    { "open", TCFG_TOK_OPEN, "O150" },
    { "or", TCFG_TOK_OR, "O600" },
    { "alternatively", TCFG_TOK_OR, "A436" },
    { "party", TCFG_TOK_PARTY, "P630" },
    { "disco", TCFG_TOK_PARTY, "D200" },
    { "patrol", TCFG_TOK_PATROL, "P364" },
    { "guard", TCFG_TOK_PATROL, "G630" },
    { "watch", TCFG_TOK_PATROL, "W320" },
    { "pause", TCFG_TOK_PAUSE, "P200" },
    { "play", TCFG_TOK_PLAY, "P400" },
    { "start", TCFG_TOK_PLAY, "S363" },
    { "resume", TCFG_TOK_PLAY, "R250" },
    { "playlist", TCFG_TOK_PLAYLIST, "P423" },
    { "previous", TCFG_TOK_PREVIOUS, "P612" },
    { "back", TCFG_TOK_PREVIOUS, "B200" },
    { "rewind", TCFG_TOK_PREVIOUS, "R530" },
    { "radio", TCFG_TOK_RADIO, "R300" },
    { "station", TCFG_TOK_RADIO, "S350" },
    { "record", TCFG_TOK_RECORD, "R263" },
    { "capture", TCFG_TOK_RECORD, "C136" },
    { "room", TCFG_TOK_ROOM, "R500" },
    { "scene", TCFG_TOK_SCENE, "S250" },
    { "mode", TCFG_TOK_SCENE, "M300" },
    { "second", TCFG_TOK_SECOND, "S253" },
    { "seconds", TCFG_TOK_SECOND, "S253" },
    { "sec", TCFG_TOK_SECOND, "S200" },
    { "seconds", TCFG_TOK_SECONDS, "S253" },
    { "set", TCFG_TOK_SET, "S300" },
    { "seventy", TCFG_TOK_SEVENTY, "S153" },
    { "70", TCFG_TOK_SEVENTY, "7000" },
    { "song", TCFG_TOK_SONG, "S520" },
    { "music", TCFG_TOK_SONG, "M200" },
    { "track", TCFG_TOK_SONG, "T620" },
    { "stop", TCFG_TOK_STOP, "S310" },
    { "halt", TCFG_TOK_STOP, "H430" },
    { "freeze", TCFG_TOK_STOP, "F620" },
    { "cancel", TCFG_TOK_STOP, "C524" },
    { "ten", TCFG_TOK_TEN, "T500" },
    { "10", TCFG_TOK_TEN, "1000" },
    { "then", TCFG_TOK_THEN, "T500" },
    { "thermostat", TCFG_TOK_THERMOSTAT, "T652" },
    { "temperature", TCFG_TOK_THERMOSTAT, "T516" },
    { "temp", TCFG_TOK_THERMOSTAT, "T510" },
    { "ac", TCFG_TOK_THERMOSTAT, "A200" },
    { "heater", TCFG_TOK_THERMOSTAT, "H360" },
    { "thirty", TCFG_TOK_THIRTY, "T630" },
    { "30", TCFG_TOK_THIRTY, "3000" },
    { "three", TCFG_TOK_THREE, "T600" },
    { "3", TCFG_TOK_THREE, "3000" },
    { "timer", TCFG_TOK_TIMER, "T560" },
    { "countdown", TCFG_TOK_TIMER, "C535" },
    { "to", TCFG_TOK_TO, "T000" },
    { "towards", TCFG_TOK_TO, "T632" },
    { "turn", TCFG_TOK_TURN, "T650" },
    { "switch", TCFG_TOK_TURN, "S320" },
    { "activate", TCFG_TOK_TURN, "A231" },
    { "power", TCFG_TOK_TURN, "P600" },
    { "two", TCFG_TOK_TWO, "T000" },
    { "2", TCFG_TOK_TWO, "2000" },
    { "unlock", TCFG_TOK_UNLOCK, "U542" },
    { "unmute", TCFG_TOK_UNMUTE, "U530" },
    { "until", TCFG_TOK_UNTIL, "U534" },
    { "up", TCFG_TOK_UP, "U100" },
    { "louder", TCFG_TOK_UP, "L360" },
    { "increase", TCFG_TOK_UP, "I526" },
    { "volume", TCFG_TOK_VOLUME, "V450" },
    { "sound", TCFG_TOK_VOLUME, "S530" },
    { "wait", TCFG_TOK_WAIT, "W300" },
    { "pause", TCFG_TOK_WAIT, "P200" },
    { "hold", TCFG_TOK_WAIT, "H430" },
    { "while", TCFG_TOK_WHILE, "W400" },
};
static const uint8_t TCFG_SYNONYM_COUNT = 168;

struct TcfgPattern {
    const uint8_t* tokens;
    uint8_t token_count;
    uint8_t action;
    const char* arg_template;
    uint8_t domain;
    uint8_t resource;
    const uint8_t* slot_types;  // 0=lit, 1=loc, 2=name, 3=device
};

enum TcfgSlotType : uint8_t { TCFG_SLOT_LIT=0, TCFG_SLOT_LOC=1, TCFG_SLOT_NM=2, TCFG_SLOT_DEV=3 };

static const uint8_t TCFG_PAT_0_TOKENS[] = { TCFG_TOK_TURN, TCFG_TOK_ON, TCFG_SLOT_LOCATION, TCFG_TOK_LIGHT };
static const uint8_t TCFG_PAT_0_SLOTS[] = { 0, 0, 1, 0 };
static const uint8_t TCFG_PAT_1_TOKENS[] = { TCFG_TOK_TURN, TCFG_TOK_ON, TCFG_SLOT_NAME, TCFG_SLOT_LOCATION, TCFG_TOK_LIGHT };
static const uint8_t TCFG_PAT_1_SLOTS[] = { 0, 0, 2, 1, 0 };
static const uint8_t TCFG_PAT_2_TOKENS[] = { TCFG_TOK_TURN, TCFG_TOK_ON, TCFG_SLOT_NAME, TCFG_TOK_LIGHT };
static const uint8_t TCFG_PAT_2_SLOTS[] = { 0, 0, 2, 0 };
static const uint8_t TCFG_PAT_3_TOKENS[] = { TCFG_TOK_TURN, TCFG_TOK_ON, TCFG_TOK_LIGHT };
static const uint8_t TCFG_PAT_3_SLOTS[] = { 0, 0, 0 };
static const uint8_t TCFG_PAT_4_TOKENS[] = { TCFG_TOK_TURN, TCFG_TOK_ON, TCFG_SLOT_LOCATION, TCFG_TOK_LIGHT };
static const uint8_t TCFG_PAT_4_SLOTS[] = { 0, 0, 1, 0 };
static const uint8_t TCFG_PAT_5_TOKENS[] = { TCFG_TOK_TURN, TCFG_TOK_OFF, TCFG_SLOT_LOCATION, TCFG_TOK_LIGHT };
static const uint8_t TCFG_PAT_5_SLOTS[] = { 0, 0, 1, 0 };
static const uint8_t TCFG_PAT_6_TOKENS[] = { TCFG_TOK_TURN, TCFG_TOK_OFF, TCFG_SLOT_NAME, TCFG_SLOT_LOCATION, TCFG_TOK_LIGHT };
static const uint8_t TCFG_PAT_6_SLOTS[] = { 0, 0, 2, 1, 0 };
static const uint8_t TCFG_PAT_7_TOKENS[] = { TCFG_TOK_TURN, TCFG_TOK_OFF, TCFG_SLOT_NAME, TCFG_TOK_LIGHT };
static const uint8_t TCFG_PAT_7_SLOTS[] = { 0, 0, 2, 0 };
static const uint8_t TCFG_PAT_8_TOKENS[] = { TCFG_TOK_TURN, TCFG_TOK_OFF, TCFG_TOK_LIGHT };
static const uint8_t TCFG_PAT_8_SLOTS[] = { 0, 0, 0 };
static const uint8_t TCFG_PAT_9_TOKENS[] = { TCFG_TOK_TURN, TCFG_TOK_ON, TCFG_SLOT_LOCATION, TCFG_TOK_FAN };
static const uint8_t TCFG_PAT_9_SLOTS[] = { 0, 0, 1, 0 };
static const uint8_t TCFG_PAT_10_TOKENS[] = { TCFG_TOK_TURN, TCFG_TOK_ON, TCFG_SLOT_NAME, TCFG_SLOT_LOCATION, TCFG_TOK_FAN };
static const uint8_t TCFG_PAT_10_SLOTS[] = { 0, 0, 2, 1, 0 };
static const uint8_t TCFG_PAT_11_TOKENS[] = { TCFG_TOK_TURN, TCFG_TOK_ON, TCFG_SLOT_NAME, TCFG_TOK_FAN };
static const uint8_t TCFG_PAT_11_SLOTS[] = { 0, 0, 2, 0 };
static const uint8_t TCFG_PAT_12_TOKENS[] = { TCFG_TOK_TURN, TCFG_TOK_ON, TCFG_TOK_FAN };
static const uint8_t TCFG_PAT_12_SLOTS[] = { 0, 0, 0 };
static const uint8_t TCFG_PAT_13_TOKENS[] = { TCFG_TOK_TURN, TCFG_TOK_OFF, TCFG_SLOT_LOCATION, TCFG_TOK_FAN };
static const uint8_t TCFG_PAT_13_SLOTS[] = { 0, 0, 1, 0 };
static const uint8_t TCFG_PAT_14_TOKENS[] = { TCFG_TOK_TURN, TCFG_TOK_OFF, TCFG_SLOT_NAME, TCFG_SLOT_LOCATION, TCFG_TOK_FAN };
static const uint8_t TCFG_PAT_14_SLOTS[] = { 0, 0, 2, 1, 0 };
static const uint8_t TCFG_PAT_15_TOKENS[] = { TCFG_TOK_TURN, TCFG_TOK_OFF, TCFG_SLOT_NAME, TCFG_TOK_FAN };
static const uint8_t TCFG_PAT_15_SLOTS[] = { 0, 0, 2, 0 };
static const uint8_t TCFG_PAT_16_TOKENS[] = { TCFG_TOK_TURN, TCFG_TOK_OFF, TCFG_TOK_FAN };
static const uint8_t TCFG_PAT_16_SLOTS[] = { 0, 0, 0 };
static const uint8_t TCFG_PAT_17_TOKENS[] = { TCFG_TOK_LOCK, TCFG_SLOT_LOCATION, TCFG_TOK_DOOR };
static const uint8_t TCFG_PAT_17_SLOTS[] = { 0, 1, 0 };
static const uint8_t TCFG_PAT_18_TOKENS[] = { TCFG_TOK_LOCK, TCFG_SLOT_NAME, TCFG_TOK_DOOR };
static const uint8_t TCFG_PAT_18_SLOTS[] = { 0, 2, 0 };
static const uint8_t TCFG_PAT_19_TOKENS[] = { TCFG_TOK_LOCK, TCFG_SLOT_NAME, TCFG_SLOT_LOCATION, TCFG_TOK_DOOR };
static const uint8_t TCFG_PAT_19_SLOTS[] = { 0, 2, 1, 0 };
static const uint8_t TCFG_PAT_20_TOKENS[] = { TCFG_TOK_UNLOCK, TCFG_SLOT_LOCATION, TCFG_TOK_DOOR };
static const uint8_t TCFG_PAT_20_SLOTS[] = { 0, 1, 0 };
static const uint8_t TCFG_PAT_21_TOKENS[] = { TCFG_TOK_UNLOCK, TCFG_SLOT_NAME, TCFG_TOK_DOOR };
static const uint8_t TCFG_PAT_21_SLOTS[] = { 0, 2, 0 };
static const uint8_t TCFG_PAT_22_TOKENS[] = { TCFG_TOK_UNLOCK, TCFG_SLOT_NAME, TCFG_SLOT_LOCATION, TCFG_TOK_DOOR };
static const uint8_t TCFG_PAT_22_SLOTS[] = { 0, 2, 1, 0 };
static const uint8_t TCFG_PAT_23_TOKENS[] = { TCFG_TOK_OPEN, TCFG_SLOT_LOCATION, TCFG_TOK_CURTAIN };
static const uint8_t TCFG_PAT_23_SLOTS[] = { 0, 1, 0 };
static const uint8_t TCFG_PAT_24_TOKENS[] = { TCFG_TOK_OPEN, TCFG_SLOT_NAME, TCFG_TOK_CURTAIN };
static const uint8_t TCFG_PAT_24_SLOTS[] = { 0, 2, 0 };
static const uint8_t TCFG_PAT_25_TOKENS[] = { TCFG_TOK_CLOSE, TCFG_SLOT_LOCATION, TCFG_TOK_CURTAIN };
static const uint8_t TCFG_PAT_25_SLOTS[] = { 0, 1, 0 };
static const uint8_t TCFG_PAT_26_TOKENS[] = { TCFG_TOK_CLOSE, TCFG_SLOT_NAME, TCFG_TOK_CURTAIN };
static const uint8_t TCFG_PAT_26_SLOTS[] = { 0, 2, 0 };
static const uint8_t TCFG_PAT_27_TOKENS[] = { TCFG_TOK_OPEN, TCFG_TOK_CURTAIN };
static const uint8_t TCFG_PAT_27_SLOTS[] = { 0, 0 };
static const uint8_t TCFG_PAT_28_TOKENS[] = { TCFG_TOK_CLOSE, TCFG_TOK_CURTAIN };
static const uint8_t TCFG_PAT_28_SLOTS[] = { 0, 0 };
static const uint8_t TCFG_PAT_29_TOKENS[] = { TCFG_TOK_SCENE, TCFG_TOK_MOVIE };
static const uint8_t TCFG_PAT_29_SLOTS[] = { 0, 0 };
static const uint8_t TCFG_PAT_30_TOKENS[] = { TCFG_TOK_SCENE, TCFG_TOK_NIGHT };
static const uint8_t TCFG_PAT_30_SLOTS[] = { 0, 0 };
static const uint8_t TCFG_PAT_31_TOKENS[] = { TCFG_TOK_SCENE, TCFG_TOK_PARTY };
static const uint8_t TCFG_PAT_31_SLOTS[] = { 0, 0 };
static const uint8_t TCFG_PAT_32_TOKENS[] = { TCFG_TOK_MOVIE, TCFG_TOK_SCENE };
static const uint8_t TCFG_PAT_32_SLOTS[] = { 0, 0 };
static const uint8_t TCFG_PAT_33_TOKENS[] = { TCFG_TOK_NIGHT, TCFG_TOK_SCENE };
static const uint8_t TCFG_PAT_33_SLOTS[] = { 0, 0 };
static const uint8_t TCFG_PAT_34_TOKENS[] = { TCFG_TOK_COME, TCFG_TOK_HERE };
static const uint8_t TCFG_PAT_34_SLOTS[] = { 0, 0 };
static const uint8_t TCFG_PAT_35_TOKENS[] = { TCFG_TOK_GO, TCFG_TOK_TO, TCFG_SLOT_LOCATION };
static const uint8_t TCFG_PAT_35_SLOTS[] = { 0, 0, 1 };
static const uint8_t TCFG_PAT_36_TOKENS[] = { TCFG_TOK_GO, TCFG_TOK_TO, TCFG_SLOT_LOCATION, TCFG_TOK_ROOM };
static const uint8_t TCFG_PAT_36_SLOTS[] = { 0, 0, 1, 0 };
static const uint8_t TCFG_PAT_37_TOKENS[] = { TCFG_TOK_GO, TCFG_TOK_TO, TCFG_SLOT_NAME, TCFG_TOK_ROOM };
static const uint8_t TCFG_PAT_37_SLOTS[] = { 0, 0, 2, 0 };
static const uint8_t TCFG_PAT_38_TOKENS[] = { TCFG_TOK_GO, TCFG_TOK_TO, TCFG_SLOT_NAME, TCFG_SLOT_LOCATION };
static const uint8_t TCFG_PAT_38_SLOTS[] = { 0, 0, 2, 1 };
static const uint8_t TCFG_PAT_39_TOKENS[] = { TCFG_TOK_GO, TCFG_TOK_TO, TCFG_SLOT_LOCATION };
static const uint8_t TCFG_PAT_39_SLOTS[] = { 0, 0, 1 };
static const uint8_t TCFG_PAT_40_TOKENS[] = { TCFG_TOK_FOLLOW, TCFG_TOK_HERE };
static const uint8_t TCFG_PAT_40_SLOTS[] = { 0, 0 };
static const uint8_t TCFG_PAT_41_TOKENS[] = { TCFG_TOK_PATROL, TCFG_SLOT_LOCATION };
static const uint8_t TCFG_PAT_41_SLOTS[] = { 0, 1 };
static const uint8_t TCFG_PAT_42_TOKENS[] = { TCFG_TOK_GO, TCFG_TOK_HOME };
static const uint8_t TCFG_PAT_42_SLOTS[] = { 0, 0 };
static const uint8_t TCFG_PAT_43_TOKENS[] = { TCFG_TOK_DOCK };
static const uint8_t TCFG_PAT_43_SLOTS[] = { 0 };
static const uint8_t TCFG_PAT_44_TOKENS[] = { TCFG_TOK_STOP };
static const uint8_t TCFG_PAT_44_SLOTS[] = { 0 };
static const uint8_t TCFG_PAT_45_TOKENS[] = { TCFG_TOK_WAIT };
static const uint8_t TCFG_PAT_45_SLOTS[] = { 0 };
static const uint8_t TCFG_PAT_46_TOKENS[] = { TCFG_TOK_PLAY, TCFG_TOK_SONG };
static const uint8_t TCFG_PAT_46_SLOTS[] = { 0, 0 };
static const uint8_t TCFG_PAT_47_TOKENS[] = { TCFG_TOK_PLAY, TCFG_TOK_RADIO };
static const uint8_t TCFG_PAT_47_SLOTS[] = { 0, 0 };
static const uint8_t TCFG_PAT_48_TOKENS[] = { TCFG_TOK_PLAY, TCFG_SLOT_NAME, TCFG_TOK_PLAYLIST };
static const uint8_t TCFG_PAT_48_SLOTS[] = { 0, 2, 0 };
static const uint8_t TCFG_PAT_49_TOKENS[] = { TCFG_TOK_PAUSE, TCFG_TOK_SONG };
static const uint8_t TCFG_PAT_49_SLOTS[] = { 0, 0 };
static const uint8_t TCFG_PAT_50_TOKENS[] = { TCFG_TOK_PAUSE };
static const uint8_t TCFG_PAT_50_SLOTS[] = { 0 };
static const uint8_t TCFG_PAT_51_TOKENS[] = { TCFG_TOK_VOLUME, TCFG_TOK_UP };
static const uint8_t TCFG_PAT_51_SLOTS[] = { 0, 0 };
static const uint8_t TCFG_PAT_52_TOKENS[] = { TCFG_TOK_VOLUME, TCFG_TOK_DOWN };
static const uint8_t TCFG_PAT_52_SLOTS[] = { 0, 0 };
static const uint8_t TCFG_PAT_53_TOKENS[] = { TCFG_TOK_MUTE };
static const uint8_t TCFG_PAT_53_SLOTS[] = { 0 };
static const uint8_t TCFG_PAT_54_TOKENS[] = { TCFG_TOK_UNMUTE };
static const uint8_t TCFG_PAT_54_SLOTS[] = { 0 };
static const uint8_t TCFG_PAT_55_TOKENS[] = { TCFG_TOK_NEXT, TCFG_TOK_SONG };
static const uint8_t TCFG_PAT_55_SLOTS[] = { 0, 0 };
static const uint8_t TCFG_PAT_56_TOKENS[] = { TCFG_TOK_PREVIOUS, TCFG_TOK_SONG };
static const uint8_t TCFG_PAT_56_SLOTS[] = { 0, 0 };
static const uint8_t TCFG_PAT_57_TOKENS[] = { TCFG_TOK_NEXT, TCFG_TOK_SONG };
static const uint8_t TCFG_PAT_57_SLOTS[] = { 0, 0 };
static const uint8_t TCFG_PAT_58_TOKENS[] = { TCFG_TOK_ARM, TCFG_TOK_ALARM };
static const uint8_t TCFG_PAT_58_SLOTS[] = { 0, 0 };
static const uint8_t TCFG_PAT_59_TOKENS[] = { TCFG_TOK_DISARM, TCFG_TOK_ALARM };
static const uint8_t TCFG_PAT_59_SLOTS[] = { 0, 0 };
static const uint8_t TCFG_PAT_60_TOKENS[] = { TCFG_TOK_CHECK, TCFG_SLOT_LOCATION, TCFG_TOK_CAMERA };
static const uint8_t TCFG_PAT_60_SLOTS[] = { 0, 1, 0 };
static const uint8_t TCFG_PAT_61_TOKENS[] = { TCFG_TOK_CHECK, TCFG_SLOT_NAME, TCFG_TOK_CAMERA };
static const uint8_t TCFG_PAT_61_SLOTS[] = { 0, 2, 0 };
static const uint8_t TCFG_PAT_62_TOKENS[] = { TCFG_TOK_CHECK, TCFG_TOK_CAMERA };
static const uint8_t TCFG_PAT_62_SLOTS[] = { 0, 0 };
static const uint8_t TCFG_PAT_63_TOKENS[] = { TCFG_TOK_PLAY, TCFG_TOK_UNKNOWN };
static const uint8_t TCFG_PAT_63_SLOTS[] = { 0, 0 };
static const uint8_t TCFG_PAT_64_TOKENS[] = { TCFG_TOK_SET, TCFG_SLOT_LOCATION, TCFG_TOK_THERMOSTAT, TCFG_TOK_TO, TCFG_TOK_SEVENTY };
static const uint8_t TCFG_PAT_64_SLOTS[] = { 0, 1, 0, 0, 0 };
static const uint8_t TCFG_PAT_65_TOKENS[] = { TCFG_TOK_SET, TCFG_TOK_THERMOSTAT, TCFG_TOK_IN, TCFG_SLOT_LOCATION };
static const uint8_t TCFG_PAT_65_SLOTS[] = { 0, 0, 0, 1 };
static const uint8_t TCFG_PAT_66_TOKENS[] = { TCFG_TOK_HEAT, TCFG_TOK_UP };
static const uint8_t TCFG_PAT_66_SLOTS[] = { 0, 0 };
static const uint8_t TCFG_PAT_67_TOKENS[] = { TCFG_TOK_COOL, TCFG_TOK_DOWN };
static const uint8_t TCFG_PAT_67_SLOTS[] = { 0, 0 };
static const uint8_t TCFG_PAT_68_TOKENS[] = { TCFG_TOK_TURN, TCFG_TOK_ON, TCFG_TOK_HEAT };
static const uint8_t TCFG_PAT_68_SLOTS[] = { 0, 0, 0 };
static const uint8_t TCFG_PAT_69_TOKENS[] = { TCFG_TOK_TURN, TCFG_TOK_ON, TCFG_TOK_COOL };
static const uint8_t TCFG_PAT_69_SLOTS[] = { 0, 0, 0 };
static const uint8_t TCFG_PAT_70_TOKENS[] = { TCFG_TOK_SET, TCFG_TOK_TIMER, TCFG_TOK_FOR, TCFG_TOK_FIVE, TCFG_TOK_MINUTES };
static const uint8_t TCFG_PAT_70_SLOTS[] = { 0, 0, 0, 0, 0 };
static const uint8_t TCFG_PAT_71_TOKENS[] = { TCFG_TOK_SET, TCFG_TOK_TIMER, TCFG_TOK_FOR, TCFG_TOK_TEN, TCFG_TOK_MINUTES };
static const uint8_t TCFG_PAT_71_SLOTS[] = { 0, 0, 0, 0, 0 };
static const uint8_t TCFG_PAT_72_TOKENS[] = { TCFG_TOK_SET, TCFG_TOK_TIMER, TCFG_TOK_FOR, TCFG_TOK_THIRTY, TCFG_TOK_MINUTES };
static const uint8_t TCFG_PAT_72_SLOTS[] = { 0, 0, 0, 0, 0 };
static const uint8_t TCFG_PAT_73_TOKENS[] = { TCFG_TOK_STOP, TCFG_TOK_TIMER };
static const uint8_t TCFG_PAT_73_SLOTS[] = { 0, 0 };

static const TcfgPattern TCFG_PATTERNS[] = {
    { TCFG_PAT_0_TOKENS, 4, TCFG_ACT_LIGHT_ON, "{location}_light", 1, 1, TCFG_PAT_0_SLOTS },
    { TCFG_PAT_1_TOKENS, 5, TCFG_ACT_LIGHT_ON, "{name}_{location}_light", 1, 1, TCFG_PAT_1_SLOTS },
    { TCFG_PAT_2_TOKENS, 4, TCFG_ACT_LIGHT_ON, "{name}_light", 1, 1, TCFG_PAT_2_SLOTS },
    { TCFG_PAT_3_TOKENS, 3, TCFG_ACT_LIGHT_ON, "default_light", 1, 1, TCFG_PAT_3_SLOTS },
    { TCFG_PAT_4_TOKENS, 4, TCFG_ACT_LIGHT_ON, "{location}_light", 1, 1, TCFG_PAT_4_SLOTS },
    { TCFG_PAT_5_TOKENS, 4, TCFG_ACT_LIGHT_OFF, "{location}_light", 1, 1, TCFG_PAT_5_SLOTS },
    { TCFG_PAT_6_TOKENS, 5, TCFG_ACT_LIGHT_OFF, "{name}_{location}_light", 1, 1, TCFG_PAT_6_SLOTS },
    { TCFG_PAT_7_TOKENS, 4, TCFG_ACT_LIGHT_OFF, "{name}_light", 1, 1, TCFG_PAT_7_SLOTS },
    { TCFG_PAT_8_TOKENS, 3, TCFG_ACT_LIGHT_OFF, "default_light", 1, 1, TCFG_PAT_8_SLOTS },
    { TCFG_PAT_9_TOKENS, 4, TCFG_ACT_FAN_ON, "{location}_fan", 1, 2, TCFG_PAT_9_SLOTS },
    { TCFG_PAT_10_TOKENS, 5, TCFG_ACT_FAN_ON, "{name}_{location}_fan", 1, 2, TCFG_PAT_10_SLOTS },
    { TCFG_PAT_11_TOKENS, 4, TCFG_ACT_FAN_ON, "{name}_fan", 1, 2, TCFG_PAT_11_SLOTS },
    { TCFG_PAT_12_TOKENS, 3, TCFG_ACT_FAN_ON, "default_fan", 1, 2, TCFG_PAT_12_SLOTS },
    { TCFG_PAT_13_TOKENS, 4, TCFG_ACT_FAN_OFF, "{location}_fan", 1, 2, TCFG_PAT_13_SLOTS },
    { TCFG_PAT_14_TOKENS, 5, TCFG_ACT_FAN_OFF, "{name}_{location}_fan", 1, 2, TCFG_PAT_14_SLOTS },
    { TCFG_PAT_15_TOKENS, 4, TCFG_ACT_FAN_OFF, "{name}_fan", 1, 2, TCFG_PAT_15_SLOTS },
    { TCFG_PAT_16_TOKENS, 3, TCFG_ACT_FAN_OFF, "default_fan", 1, 2, TCFG_PAT_16_SLOTS },
    { TCFG_PAT_17_TOKENS, 3, TCFG_ACT_LOCK, "{location}_door", 1, 3, TCFG_PAT_17_SLOTS },
    { TCFG_PAT_18_TOKENS, 3, TCFG_ACT_LOCK, "{name}_door", 1, 3, TCFG_PAT_18_SLOTS },
    { TCFG_PAT_19_TOKENS, 4, TCFG_ACT_LOCK, "{name}_{location}_door", 1, 3, TCFG_PAT_19_SLOTS },
    { TCFG_PAT_20_TOKENS, 3, TCFG_ACT_UNLOCK, "{location}_door", 1, 3, TCFG_PAT_20_SLOTS },
    { TCFG_PAT_21_TOKENS, 3, TCFG_ACT_UNLOCK, "{name}_door", 1, 3, TCFG_PAT_21_SLOTS },
    { TCFG_PAT_22_TOKENS, 4, TCFG_ACT_UNLOCK, "{name}_{location}_door", 1, 3, TCFG_PAT_22_SLOTS },
    { TCFG_PAT_23_TOKENS, 3, TCFG_ACT_CURTAIN_OPEN, "{location}", 1, 4, TCFG_PAT_23_SLOTS },
    { TCFG_PAT_24_TOKENS, 3, TCFG_ACT_CURTAIN_OPEN, "{name}", 1, 4, TCFG_PAT_24_SLOTS },
    { TCFG_PAT_25_TOKENS, 3, TCFG_ACT_CURTAIN_CLOSE, "{location}", 1, 4, TCFG_PAT_25_SLOTS },
    { TCFG_PAT_26_TOKENS, 3, TCFG_ACT_CURTAIN_CLOSE, "{name}", 1, 4, TCFG_PAT_26_SLOTS },
    { TCFG_PAT_27_TOKENS, 2, TCFG_ACT_CURTAIN_OPEN, "living", 1, 4, TCFG_PAT_27_SLOTS },
    { TCFG_PAT_28_TOKENS, 2, TCFG_ACT_CURTAIN_CLOSE, "living", 1, 4, TCFG_PAT_28_SLOTS },
    { TCFG_PAT_29_TOKENS, 2, TCFG_ACT_SCENE, "movie", 1, 5, TCFG_PAT_29_SLOTS },
    { TCFG_PAT_30_TOKENS, 2, TCFG_ACT_SCENE, "night", 1, 5, TCFG_PAT_30_SLOTS },
    { TCFG_PAT_31_TOKENS, 2, TCFG_ACT_SCENE, "party", 1, 5, TCFG_PAT_31_SLOTS },
    { TCFG_PAT_32_TOKENS, 2, TCFG_ACT_SCENE, "movie", 1, 5, TCFG_PAT_32_SLOTS },
    { TCFG_PAT_33_TOKENS, 2, TCFG_ACT_SCENE, "night", 1, 5, TCFG_PAT_33_SLOTS },
    { TCFG_PAT_34_TOKENS, 2, TCFG_ACT_COME_HERE, nullptr, 2, 6, TCFG_PAT_34_SLOTS },
    { TCFG_PAT_35_TOKENS, 3, TCFG_ACT_NAV_GO, "{location}", 2, 6, TCFG_PAT_35_SLOTS },
    { TCFG_PAT_36_TOKENS, 4, TCFG_ACT_NAV_GO, "{location}", 2, 6, TCFG_PAT_36_SLOTS },
    { TCFG_PAT_37_TOKENS, 4, TCFG_ACT_NAV_GO, "{name}_room", 2, 6, TCFG_PAT_37_SLOTS },
    { TCFG_PAT_38_TOKENS, 4, TCFG_ACT_NAV_GO, "{name}_{location}", 2, 6, TCFG_PAT_38_SLOTS },
    { TCFG_PAT_39_TOKENS, 3, TCFG_ACT_NAV_GO, "{location}", 2, 6, TCFG_PAT_39_SLOTS },
    { TCFG_PAT_40_TOKENS, 2, TCFG_ACT_FOLLOW_ME, nullptr, 2, 6, TCFG_PAT_40_SLOTS },
    { TCFG_PAT_41_TOKENS, 2, TCFG_ACT_PATROL, "{location}", 2, 6, TCFG_PAT_41_SLOTS },
    { TCFG_PAT_42_TOKENS, 2, TCFG_ACT_NAV_HOME, nullptr, 2, 6, TCFG_PAT_42_SLOTS },
    { TCFG_PAT_43_TOKENS, 1, TCFG_ACT_NAV_DOCK, nullptr, 2, 6, TCFG_PAT_43_SLOTS },
    { TCFG_PAT_44_TOKENS, 1, TCFG_ACT_STOP, nullptr, 2, 6, TCFG_PAT_44_SLOTS },
    { TCFG_PAT_45_TOKENS, 1, TCFG_ACT_WAIT, nullptr, 2, 6, TCFG_PAT_45_SLOTS },
    { TCFG_PAT_46_TOKENS, 2, TCFG_ACT_MEDIA_PLAY, "music", 3, 7, TCFG_PAT_46_SLOTS },
    { TCFG_PAT_47_TOKENS, 2, TCFG_ACT_MEDIA_PLAY, "radio", 3, 7, TCFG_PAT_47_SLOTS },
    { TCFG_PAT_48_TOKENS, 3, TCFG_ACT_MEDIA_PLAY, "{name}", 3, 7, TCFG_PAT_48_SLOTS },
    { TCFG_PAT_49_TOKENS, 2, TCFG_ACT_MEDIA_PAUSE, nullptr, 3, 7, TCFG_PAT_49_SLOTS },
    { TCFG_PAT_50_TOKENS, 1, TCFG_ACT_MEDIA_PAUSE, nullptr, 3, 7, TCFG_PAT_50_SLOTS },
    { TCFG_PAT_51_TOKENS, 2, TCFG_ACT_VOLUME_UP, nullptr, 3, 7, TCFG_PAT_51_SLOTS },
    { TCFG_PAT_52_TOKENS, 2, TCFG_ACT_VOLUME_DOWN, nullptr, 3, 7, TCFG_PAT_52_SLOTS },
    { TCFG_PAT_53_TOKENS, 1, TCFG_ACT_MUTE, nullptr, 3, 7, TCFG_PAT_53_SLOTS },
    { TCFG_PAT_54_TOKENS, 1, TCFG_ACT_UNMUTE, nullptr, 3, 7, TCFG_PAT_54_SLOTS },
    { TCFG_PAT_55_TOKENS, 2, TCFG_ACT_NEXT_TRACK, nullptr, 3, 7, TCFG_PAT_55_SLOTS },
    { TCFG_PAT_56_TOKENS, 2, TCFG_ACT_PREV_TRACK, nullptr, 3, 7, TCFG_PAT_56_SLOTS },
    { TCFG_PAT_57_TOKENS, 2, TCFG_ACT_NEXT_TRACK, nullptr, 3, 7, TCFG_PAT_57_SLOTS },
    { TCFG_PAT_58_TOKENS, 2, TCFG_ACT_ALARM_ARM, nullptr, 4, 8, TCFG_PAT_58_SLOTS },
    { TCFG_PAT_59_TOKENS, 2, TCFG_ACT_ALARM_DISARM, nullptr, 4, 8, TCFG_PAT_59_SLOTS },
    { TCFG_PAT_60_TOKENS, 3, TCFG_ACT_CAMERA_VIEW, "{location}", 4, 9, TCFG_PAT_60_SLOTS },
    { TCFG_PAT_61_TOKENS, 3, TCFG_ACT_CAMERA_VIEW, "{name}", 4, 9, TCFG_PAT_61_SLOTS },
    { TCFG_PAT_62_TOKENS, 2, TCFG_ACT_CAMERA_VIEW, "all", 4, 9, TCFG_PAT_62_SLOTS },
    { TCFG_PAT_63_TOKENS, 2, TCFG_ACT_CAMERA_RECORD, nullptr, 4, 9, TCFG_PAT_63_SLOTS },
    { TCFG_PAT_64_TOKENS, 5, TCFG_ACT_TEMP_SET, "{location}_70", 5, 10, TCFG_PAT_64_SLOTS },
    { TCFG_PAT_65_TOKENS, 4, TCFG_ACT_TEMP_ZONE, "{location}", 5, 10, TCFG_PAT_65_SLOTS },
    { TCFG_PAT_66_TOKENS, 2, TCFG_ACT_TEMP_UP, nullptr, 5, 10, TCFG_PAT_66_SLOTS },
    { TCFG_PAT_67_TOKENS, 2, TCFG_ACT_TEMP_DOWN, nullptr, 5, 10, TCFG_PAT_67_SLOTS },
    { TCFG_PAT_68_TOKENS, 3, TCFG_ACT_HEAT_ON, nullptr, 5, 10, TCFG_PAT_68_SLOTS },
    { TCFG_PAT_69_TOKENS, 3, TCFG_ACT_COOL_ON, nullptr, 5, 10, TCFG_PAT_69_SLOTS },
    { TCFG_PAT_70_TOKENS, 5, TCFG_ACT_TIMER_SET, "5_min", 6, 11, TCFG_PAT_70_SLOTS },
    { TCFG_PAT_71_TOKENS, 5, TCFG_ACT_TIMER_SET, "10_min", 6, 11, TCFG_PAT_71_SLOTS },
    { TCFG_PAT_72_TOKENS, 5, TCFG_ACT_TIMER_SET, "30_min", 6, 11, TCFG_PAT_72_SLOTS },
    { TCFG_PAT_73_TOKENS, 2, TCFG_ACT_TIMER_CANCEL, nullptr, 6, 11, TCFG_PAT_73_SLOTS },
};

static const char* TCFG_ACTION_NAMES[] = {
    "NONE",
    "SEQ_AND",
    "SEQ_THEN",
    "SEQ_AFTER",
    "SEQ_BEFORE",
    "SEQ_IF",
    "SEQ_UNTIL",
    "SEQ_WHILE",
    "LIGHT_ON",
    "LIGHT_OFF",
    "FAN_ON",
    "FAN_OFF",
    "LOCK",
    "UNLOCK",
    "CURTAIN_OPEN",
    "CURTAIN_CLOSE",
    "SCENE",
    "COME_HERE",
    "NAV_GO",
    "FOLLOW_ME",
    "PATROL",
    "NAV_HOME",
    "NAV_DOCK",
    "STOP",
    "WAIT",
    "MEDIA_PLAY",
    "MEDIA_PAUSE",
    "VOLUME_UP",
    "VOLUME_DOWN",
    "MUTE",
    "UNMUTE",
    "NEXT_TRACK",
    "PREV_TRACK",
    "ALARM_ARM",
    "ALARM_DISARM",
    "CAMERA_VIEW",
    "CAMERA_RECORD",
    "TEMP_SET",
    "TEMP_ZONE",
    "TEMP_UP",
    "TEMP_DOWN",
    "HEAT_ON",
    "COOL_ON",
    "TIMER_SET",
    "TIMER_CANCEL",
};

static const char* TCFG_DOMAIN_NAMES[] = {
    "general", "smarthome", "robot", "media", "security", "climate", "timer",
};

#endif // TINYCFG_SMART_WORLD_GRAMMAR_H
